services:
  ros:
    build:
      context: .
      dockerfile: docker/Dockerfile
      args:
        L4T_TAG: ${L4T_TAG}
    image: ${IMAGE_NAME}:${IMAGE_TAG}
    container_name: plevelai_ros
    runtime: nvidia
    environment:
      - NVIDIA_VISIBLE_DEVICES=all
      - NVIDIA_DRIVER_CAPABILITIES=all
      - DISPLAY=${DISPLAY}
      - QT_X11_NO_MITSHM=1
      - ROS_DISTRO=${ROS_DISTRO}
    volumes:
      - ./src:/home/ros/ws/src:rw
      - /tmp/.X11-unix:/tmp/.X11-unix:rw
    devices:
      - /dev/video0:/dev/video0
    network_mode: host
    privileged: true
    command: >
      bash -lc "ros2 launch plevelai_control plevelai_mock_pipeline.launch.py"
